# yaml-language-server: $schema=ai.yaml.json

deployments:
  - name: gpt-35-turbo
    model:
      format: OpenAI
      name: gpt-35-turbo
      version: "0613"
    sku:
      name: Standard
      capacity: 20
  - name: gpt-4
    model:
      format: OpenAI
      name: gpt-4
      version: "0613"
    sku:
      name: Standard
      capacity: 10
  - name: text-embedding-3-large
    model:
      format: OpenAI
      name: text-embedding-3-large
      version: "1"
    sku:
      name: "Standard"
      capacity: 30
